package fr.zeguigui.adventofcode;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class UnitTest {

    @Test
    void test() {

        Cpu cpu = new Cpu(1);
        cpu.addX(15);
        cpu.addX(-11);
        cpu.addX(6);
        cpu.addX(-3);
        cpu.addX(5);
        cpu.addX(-1);
        cpu.addX(-8);
        cpu.addX(13);
        cpu.addX(4);
        cpu.noop();
        cpu.addX(-1);
        cpu.addX(5);
        cpu.addX(-1);
        cpu.addX(5);
        cpu.addX(-1);
        cpu.addX(5);
        cpu.addX(-1);
        cpu.addX(5);
        cpu.addX(-1);
        cpu.addX(-35);
        cpu.addX(1);
        cpu.addX(24);
        cpu.addX(-19);
        cpu.addX(1);
        cpu.addX(16);
        cpu.addX(-11);
        cpu.noop();
        cpu.noop();
        cpu.addX(21);
        cpu.addX(-15);
        cpu.noop();
        cpu.noop();
        cpu.addX(-3);
        cpu.addX(9);
        cpu.addX(1);
        cpu.addX(-3);
        cpu.addX(8);
        cpu.addX(1);
        cpu.addX(5);
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.addX(-36);
        cpu.noop();
        cpu.addX(1);
        cpu.addX(7);
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.addX(2);
        cpu.addX(6);
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.addX(1);
        cpu.noop();
        cpu.noop();
        cpu.addX(7);
        cpu.addX(1);
        cpu.noop();
        cpu.addX(-13);
        cpu.addX(13);
        cpu.addX(7);
        cpu.noop();
        cpu.addX(1);
        cpu.addX(-33);
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.addX(2);
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.addX(8);
        cpu.noop();
        cpu.addX(-1);
        cpu.addX(2);
        cpu.addX(1);
        cpu.noop();
        cpu.addX(17);
        cpu.addX(-9);
        cpu.addX(1);
        cpu.addX(1);
        cpu.addX(-3);
        cpu.addX(11);
        cpu.noop();
        cpu.noop();
        cpu.addX(1);
        cpu.noop();
        cpu.addX(1);
        cpu.noop();
        cpu.noop();
        cpu.addX(-13);
        cpu.addX(-19);
        cpu.addX(1);
        cpu.addX(3);
        cpu.addX(26);
        cpu.addX(-30);
        cpu.addX(12);
        cpu.addX(-1);
        cpu.addX(3);
        cpu.addX(1);
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.addX(-9);
        cpu.addX(18);
        cpu.addX(1);
        cpu.addX(2);
        cpu.noop();
        cpu.noop();
        cpu.addX(9);
        cpu.noop();
        cpu.noop();
        cpu.noop();
        cpu.addX(-1);
        cpu.addX(2);
        cpu.addX(-37);
        cpu.addX(1);
        cpu.addX(3);
        cpu.noop();
        cpu.addX(15);
        cpu.addX(-21);
        cpu.addX(22);
        cpu.addX(-6);
        cpu.addX(1);
        cpu.noop();
        cpu.addX(2);
        cpu.addX(1);
        cpu.noop();
        cpu.addX(-10);
        cpu.noop();
        cpu.noop();
        cpu.addX(20);
        cpu.addX(1);
        cpu.addX(2);
        cpu.addX(2);
        cpu.addX(-6);
        cpu.addX(-11);
        cpu.noop();
        cpu.noop();
        cpu.noop();
        assertEquals(21, cpu.getHistory(20));
        assertEquals(19, cpu.getHistory(60));
        assertEquals(18, cpu.getHistory(100));
        assertEquals(21, cpu.getHistory(140));
        assertEquals(16, cpu.getHistory(180));
        assertEquals(18, cpu.getHistory(220));
        assertEquals(13140, cpu.getSignalStrength());
        System.out.println(cpu.getCrt());
    }

}